language:
  - minimal

services:
  - docker

install:
  - docker pull jjmerelo/raku-test
  - docker images
  - rakudobrew build zef
  - zef -v install SVG
  - zef -v install SVG::Plot
  - zef -v install Math::Polygons 
  - travis_retry zef install --depsonly .

script: docker run -t -v  $TRAVIS_BUILD_DIR:/test jjmerelo/raku-test
